[Feature] Workflow Composer
HugoByte/aurras-event-manager pull request #22
Opened 2022-06-14 10:39 UTC by shreyasbhat0

# Pull Request Template

## Description

Workflow composer is responsible  for composing and deploying the necessary workflows.

### Components  

* Workflow Provider
* Workflow Config File
* Macros
* Operators
* Rust Boilerplate code

To create a workflow, the only necessary input is the `Workflow Config file`. The composition, direction of flow and actions are laid out in the Workflow Config file. This `Workflow Config file` is parsed by `Workflow Provider` from Tackle box, which in turn creates rust package for workflow with predefined `Rust Boilerplate code` , `Macros` , `Operator` and can be deployed to necessary environment for execution . 

Please select the options that are relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [x] Pull Request follow only a single responsibility.
- [x] Code follows the style guidelines of this project
- [x] Performed a self-review of my own code
- [x] Commented my code, particularly in hard-to-understand areas
- [x] Made corresponding changes to the documentation
- [x] Changes generate no new warnings
- [ ] Added tests that prove fix is effective or the feature works
- [ ] New and existing unit tests pass locally with the changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] Checked the code and corrected any misspellings

2022-06-22 11:13 UTC, MuhammedIrfan commented on workflow/openwhisk_macro/src/lib.rs
> +
Remove line break

2022-06-22 12:22 UTC, MuhammedIrfan requested changes

2022-06-22 12:22 UTC, MuhammedIrfan commented on workflow/openwhisk_macro/src/lib.rs
> +
Remove line break

2022-06-22 12:22 UTC, MuhammedIrfan commented on workflow/openwhisk_macro/src/lib.rs
> +
Remove line break

2022-06-22 12:22 UTC, MuhammedIrfan commented on workflow/openwhisk_macro/src/lib.rs
> +
Remove line break

2022-06-22 12:22 UTC, MuhammedIrfan commented on workflow/openwhisk_macro/src/lib.rs
> +
Remove line break

2022-06-22 12:22 UTC, MuhammedIrfan commented on workflow/openwhisk_macro/src/lib.rs
> +
Remove line break

2022-06-22 12:22 UTC, MuhammedIrfan commented on workflow/openwhisk_macro/src/lib.rs
> +                        .invoke(&self.action_name, serde_json::to_value(self.input.clone()).unwrap(), true, true).unwrap();
add line break

2022-06-22 12:22 UTC, MuhammedIrfan commented on workflow/openwhisk_macro/src/lib.rs
> +
Remove line break

2022-06-22 12:22 UTC, MuhammedIrfan commented on workflow/openwhisk_macro/src/lib.rs
> +            fn get_action_name(&self) -> String {
get_action_name to action_name as return reference &str

2022-06-22 12:22 UTC, MuhammedIrfan commented on workflow/openwhisk_macro/src/lib.rs
> +    };
Add line break

2022-06-22 12:22 UTC, MuhammedIrfan commented on workflow/openwhisk_macro/src/lib.rs
> +            property_map.insert(seg.ident.to_string().to_string(), value.clone());
remove .to_string()

2022-06-22 12:22 UTC, MuhammedIrfan commented on workflow/openwhisk_macro/src/lib.rs
> +            fn run(&mut self){
Return as result to handle error outside

2022-06-22 12:22 UTC, MuhammedIrfan commented on workflow/openwhisk_macro/src/lib.rs
> +                        .invoke(&self.action_name, serde_json::to_value(self.input.clone()).unwrap(), true, true).unwrap();
Convert to recoverable errors

2022-06-22 12:22 UTC, MuhammedIrfan commented on workflow/openwhisk_macro/src/lib.rs
> +                    self.output = serde_json::from_value(result).unwrap();
Convert to recoverable errors

2022-06-22 12:22 UTC, MuhammedIrfan commented on workflow/providers/hooks/constants.py
> +    pub fn init(&mut self, flow: Option<Box<dyn FlowExecutor>>) -> &mut Self {{
Add line break

2022-06-22 12:22 UTC, MuhammedIrfan commented on workflow/providers/hooks/functions.py
> +            for key, values in task_store_copy[flow['task_name']].items():
key:value to field: type

2022-06-22 12:22 UTC, MuhammedIrfan commented on workflow/providers/hooks/functions.py
> +    model_prize_list : HashMap<{depend_task_type_map},{current_task_type_map}>
Change to field_name

2022-06-22 13:14 UTC, shreyasbhat0 commented on workflow/openwhisk_macro/src/lib.rs
> +    };
Fixed

2022-06-22 13:14 UTC, shreyasbhat0 commented on workflow/openwhisk_macro/src/lib.rs
> +                    self.output = serde_json::from_value(result).unwrap();
Handled error to recoverable

2022-06-22 13:14 UTC, shreyasbhat0 commented on workflow/providers/hooks/constants.py
> +    pub fn init(&mut self, flow: Option<Box<dyn FlowExecutor>>) -> &mut Self {{
Fixed line break

2022-06-22 13:14 UTC, shreyasbhat0 commented on workflow/openwhisk_macro/src/lib.rs
> +                        .invoke(&self.action_name, serde_json::to_value(self.input.clone()).unwrap(), true, true).unwrap();
Fixed

2022-06-22 13:15 UTC, shreyasbhat0 commented on workflow/openwhisk_macro/src/lib.rs
> +
Fixed

2022-06-22 13:15 UTC, shreyasbhat0 commented on workflow/openwhisk_macro/src/lib.rs
> +
Fixed

2022-06-22 13:15 UTC, shreyasbhat0 commented on workflow/openwhisk_macro/src/lib.rs
> +
fixed

2022-06-22 13:15 UTC, shreyasbhat0 commented on workflow/openwhisk_macro/src/lib.rs
> +
fixed

2022-06-22 13:15 UTC, shreyasbhat0 commented on workflow/openwhisk_macro/src/lib.rs
> +            fn get_action_name(&self) -> String {
fixed

2022-06-22 13:15 UTC, shreyasbhat0 commented on workflow/openwhisk_macro/src/lib.rs
> +
fixed

2022-06-22 13:15 UTC, shreyasbhat0 commented on workflow/openwhisk_macro/src/lib.rs
> +                        .invoke(&self.action_name, serde_json::to_value(self.input.clone()).unwrap(), true, true).unwrap();
fixed

2022-06-22 13:16 UTC, shreyasbhat0 commented on workflow/openwhisk_macro/src/lib.rs
> +            fn run(&mut self){
fixed

2022-06-22 13:16 UTC, shreyasbhat0 commented on workflow/openwhisk_macro/src/lib.rs
> +            property_map.insert(seg.ident.to_string().to_string(), value.clone());
fixed

2022-06-23 05:27 UTC, shreyasbhat0 commented on workflow/providers/hooks/functions.py
> +            for key, values in task_store_copy[flow['task_name']].items():
fixed

2022-06-23 05:27 UTC, shreyasbhat0 commented on workflow/providers/hooks/functions.py
> +    model_prize_list : HashMap<{depend_task_type_map},{current_task_type_map}>
fixed Changes mentioned

2022-06-24 08:31 UTC, MuhammedIrfan approved these changes

2022-06-24 08:32 UTC, MuhammedIrfan commented on workflow/openwhisk_macro/src/lib.rs
> +    };
Add a line break

2022-06-24 08:34 UTC, merged